# Mongo DB
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/bootex?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#    username: bootuser
#    password: 1234


spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/short-url