# Mongo DB
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/bootex?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#    username: bootuser
#    password: 1234

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: short-url